---
build_from:
  aarch64: globalping/globalping-probe:0.52.1
  amd64: globalping/globalping-probe:0.52.1
  armv7: globalping/globalping-probe:0.52.1
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
